version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./src/nginx/Dockerfile
#    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"

  uwsgi:
    build:
      context: .
      dockerfile: ./src/uwsgi/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src/uwsgi/app:/var/www/app
