version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./src/nginx/Dockerfile
    ports:
      - "443:443"
  uwsgi:
    build:
      context: .
      dockerfile: ./src/uwsgi/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src/uwsgi/app:/var/www/app
    environment:
      - 'SECRET_KEY=$SECRET_KEY'
      - 'MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD'
      - 'PEPPER:$PEPPER'
  db:
    image: mariadb
    logging:
      driver: none
    environment:
      - 'MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD'